#ifndef ASSUMPTIONS_H
    #define ASSUMPTIONS_H
    
    #define MAXUSERINPUTLENGTH 100
    #define MAXINPUTFILELENGTH 10
    #define QUITSYMBOL "QUIT"
    
    #define NUMBEROFSCHEDULINGALGORITHMS 6

    
#endif

